# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.ipynb

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [40]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Administrator/anaconda3/Library/include
    lib directory: C:/Users/Administrator/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: wi

#### 3. Create a null vector of size 10 (★☆☆)

In [39]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [49]:
array = np.zeros(10)

memory_size_manual = array.size * array.itemsize
print("Memory size:", memory_size_manual)

Memory size: 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [48]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [50]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [52]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [51]:
vector = np.arange(10, 50)
reverse_vector = vector[::-1]

print(reverse_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [43]:
meta_data = np.array([[0, 1, 2],
                      [3, 4, 5],
                      [6, 7, 8]])
print(meta_data)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [42]:
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
print(non_zero_indices[0])

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [54]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [44]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.57397582 0.80715273 0.75980715]
  [0.12146324 0.16126136 0.19693708]
  [0.53983271 0.0296828  0.61091959]]

 [[0.29926438 0.18396502 0.85315048]
  [0.76164044 0.62385314 0.05095066]
  [0.2481116  0.91666317 0.88735894]]

 [[0.17543391 0.05448794 0.88657524]
  [0.37323495 0.45861524 0.01473972]
  [0.16149783 0.06190926 0.36101308]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [45]:
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()

print(Zmin, Zmax)

0.008520414872679072 0.9894910231066969


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [41]:
random_vector = np.random.random(30)
mean_value = random_vector.mean()

print("Random Vector:", random_vector)
print("Mean Value:", mean_value)


Random Vector: [0.72585786 0.28270962 0.23912495 0.7992695  0.31131123 0.10587117
 0.89103247 0.25390174 0.9756632  0.66559572 0.83790357 0.65933143
 0.6674165  0.88687618 0.71729837 0.15834758 0.70340281 0.64865636
 0.57651374 0.63506275 0.19672274 0.40921514 0.57168811 0.03962442
 0.84641997 0.1883184  0.58061446 0.23821023 0.63844495 0.90223702]
Mean Value: 0.5450880735632144


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [46]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0

print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [55]:
Z = np.ones((5, 5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [13]:
print(0 * np.nan)            
print(np.nan == np.nan)      
print(np.inf > np.nan)       
print(np.nan - np.nan)       
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)        

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [14]:
Z = np.diag(1 + np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [15]:
Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [16]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [18]:
Z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [19]:
Z = np.random.random((5, 5))
Z = (Z - np.mean(Z)) / np.std(Z)
print(Z)

[[ 0.46942921 -0.40969191 -1.21433524  0.68053567  1.18809771]
 [ 1.06894588 -1.4182397   1.08128388 -0.04246129 -1.45388386]
 [-1.26402596  1.0180621   1.2144825   1.18490955 -1.520129  ]
 [-1.56456177 -0.54669796 -0.62331883  0.5556103  -0.24174191]
 [-0.40977862  1.11899395  0.82337024  0.97498486 -0.66983981]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [20]:
color = np.dtype([
    ("r", np.ubyte),
    ("g", np.ubyte),
    ("b", np.ubyte),
    ("a", np.ubyte)
])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [21]:
Z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [22]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [33]:
Z = np.arange(10)
print(Z**Z)       
print(2 << Z >> 2)
print(Z <- Z)     
print(1j*Z)       
print(Z/1/1)      # Z<Z>Z is not legal

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [8]:
import numpy as np
print(np.array(0) / np.array(0))  
print(np.array(0) // np.array(0))   
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Administrator\AppData\Local\Temp\ipykernel_3104\3410865368.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Administrator\AppData\Local\Temp\ipykernel_3104\3410865368.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Administrator\AppData\Local\Temp\ipykernel_3104\3410865368.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [3]:
import numpy as np

Z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z))


[ -1. -10.   1.   2.   4.  -5.  -6.  10.   2.   4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [4]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 3 5 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [9]:
# Temporary ignore warnings
with np.errstate(all="ignore"):
    Z = np.array([1]) / 0  # No warning shown

# Permanently ignore
defaults = np.seterr(all="ignore")
Z = np.array([1]) / 0
np.seterr(**defaults)  # Restore settings


{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [10]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) 

False


C:\Users\Administrator\AppData\Local\Temp\ipykernel_3104\1372900712.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [14]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2024-11-15 2024-11-16 2024-11-17


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [15]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [16]:
A = np.ones(3) * 1
B = np.ones(3) * 2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
print(A)

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [17]:
Z = np.random.uniform(0, 10, 10)
print(Z - Z % 1)  
print(Z // 1)     
print(np.floor(Z))  
print(Z.astype(int))
print(np.trunc(Z))  

[0. 3. 1. 7. 8. 4. 4. 1. 2. 9.]
[0. 3. 1. 7. 8. 4. 4. 1. 2. 9.]
[0. 3. 1. 7. 8. 4. 4. 1. 2. 9.]
[0 3 1 7 8 4 4 1 2 9]
[0. 3. 1. 7. 8. 4. 4. 1. 2. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [19]:
Z = np.zeros((5, 5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [20]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [21]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [22]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.14020339 0.24166533 0.31240342 0.34432248 0.41760581 0.41899492
 0.62528959 0.81222328 0.90667352 0.94661099]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [23]:
# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [26]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
print(np.array_equal(A, B)) 
print(np.allclose(A, B))    

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [97]:
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [31]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R, T)


[0.72595941 0.76243195 0.63568511 0.54302263 0.79103627 0.26281309
 0.73741845 0.88654023 1.13850419 1.06659894] [1.36573283 1.12055589 0.44555525 1.42692991 0.75895914 0.50174103
 0.44081302 0.63861716 0.7562443  0.89283339]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [33]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.15432649 0.64461687 0.         0.30825292 0.1170089  0.2331852
 0.69388893 0.61809215 0.342045   0.3576914 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [34]:
Z = np.zeros((5, 5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(Z)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [35]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)


[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [36]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min, np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min, np.finfo(dtype).max, np.finfo(dtype).eps)


-128 127
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-3.4028235e+38 3.4028235e+38 1.1920929e-07
-1.7976931348623157e+308 1.7976931348623157e+308 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [42]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40, 40))
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [40]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(Z - v)).argmin()
print(Z[index])


52


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [95]:
Z = np.zeros(10, dtype=[('position', [('x', float), ('y', float)]),
                        ('color', [('r', float), ('g', float), ('b', float)])])
print(Z)


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [94]:
Z = np.random.random((100, 2))
D = np.sqrt(np.sum((Z[:, None, :] - Z[None, :, :])**2, axis=-1))
print(D)


[[0.         0.88252157 0.74313933 0.66361103 0.88525709 0.74038292
  0.41695506 0.71596446 0.11667204 0.49436676 0.3617975  0.14346271
  0.91609158 0.75933328 0.92219672 0.18441047 0.42165386 0.89200136
  0.54863913 0.97498868 0.45130285 0.70727663 0.60637828 0.88663893
  0.47749467 0.54157755 0.93049021 0.91547104 0.4433732  0.39094986
  0.28210875 0.24336636 0.82493779 0.84729899 0.97598714 0.12874158
  0.49516768 0.08399375 0.50007846 0.46119004 0.09471629 0.555235
  0.12956759 0.95825391 0.61514936 0.6859889  0.17044159 0.32998644
  0.30271827 0.63475044 0.28328748 0.08130565 0.67799967 0.87691682
  0.04190939 0.65533023 0.61457829 0.47828091 0.53112485 0.5746906
  0.70991854 0.3121035  0.74925549 0.21819786 0.67437812 0.97784912
  0.71475393 1.02926727 0.83495696 0.22808592 1.16180353 0.82683574
  0.48883858 0.44466314 0.8019967  1.02361884 0.49237756 0.93957183
  0.75614815 0.98074624 0.24895103 1.01608217 0.38890297 0.73285242
  0.13094402 0.60722209 0.11607765 0.53604125 0.927

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [93]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)


[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [92]:
from io import StringIO
text = """1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""
data = np.genfromtxt(StringIO(text), delimiter=",", dtype=np.float32)
print(data)


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [91]:
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [90]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X**2 + Y**2)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D - mu)**2 / (2.0 * sigma**2)))
print(G)



[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [89]:
n = 5
p = 3
Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)


[[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [88]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


[[-0.21354079 -0.01117889 -0.25556861  0.20299148  0.18536675  0.57402805
  -0.33214516 -0.19187203  0.39754793 -0.35562873]
 [-0.11450485  0.02425535  0.0062861   0.29040808  0.1240724   0.1135242
  -0.01914172 -0.05063473 -0.0891782  -0.28508663]
 [ 0.06635288 -0.30762753 -0.43113797  0.06844403 -0.21645158  0.22262919
   0.46825047  0.3664175  -0.41456891  0.17769193]
 [-0.24065661  0.18500861 -0.45387911  0.25878094 -0.52020182  0.36527965
   0.23308892  0.2084823   0.38016164 -0.41606451]
 [ 0.10229388  0.02199773 -0.26921136 -0.11892316  0.54082785 -0.03280314
  -0.1849015  -0.28809628 -0.33801937  0.56683535]]


#### 59. How to sort an array by the nth column? (★★☆)

In [87]:
Z = np.random.randint(0, 10, (5, 5))
print(Z[Z[:, 1].argsort()])  # Sort by second column


[[7 0 3 3 8]
 [6 1 7 8 6]
 [8 6 7 3 7]
 [3 6 5 2 2]
 [2 9 6 6 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [86]:
Z = np.random.randint(0, 3, (3, 10))
print((Z == 0).all(axis=0))  # Boolean array indicating null columns


[False False False False False False False False False False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [85]:
Z = np.random.uniform(0, 1, 10)
v = 0.5
print(Z[np.abs(Z - v).argmin()])


0.5078357726991911


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [84]:
A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [83]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

Z = NamedArray(np.arange(10), "Sample Array")
print(Z.name)


Sample Array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [82]:
Z = np.ones(10)
I = np.random.randint(0, len(Z), 20)
np.add.at(Z, I, 1)
print(Z)


[3. 2. 2. 5. 2. 1. 8. 1. 5. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [81]:
X = [1, 2, 3, 4, 5]
I = [0, 1, 2, 3, 4]
F = np.zeros(5)
np.add.at(F, I, X)
print(F)


[1. 2. 3. 4. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [80]:
w, h = 16, 16
I = np.random.randint(0, 256, (h, w, 3), dtype=np.uint8)
F = I[..., 0]*256*256 + I[..., 1]*256 + I[..., 2]
print(len(np.unique(F)))


255


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [79]:
A = np.random.randint(0, 10, (3, 4, 3, 3))
sum_over_last_two = A.sum(axis=(-2, -1))
print(sum_over_last_two)


[[51 34 43 31]
 [38 32 40 36]
 [42 41 45 48]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [78]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
means = np.array([D[S == i].mean() for i in np.unique(S)])
print(means)


[0.55811885 0.45003444 0.45931591 0.43206517 0.52579728 0.39364598
 0.48136689 0.6376591  0.61779439 0.54645836]


#### 69. How to get the diagonal of a dot product? (★★★)

In [77]:
A = np.random.rand(4, 4)
B = np.random.rand(4, 4)
print(np.einsum('ij,ji->i', A, B))


[0.88202083 0.10886717 0.87897484 0.48212614]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [76]:
Z = np.array([1, 2, 3, 4, 5])
R = np.zeros(len(Z) + (len(Z)-1)*3)
R[::4] = Z
print(R)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [75]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))
print(A * B[:, :, None])  # Broadcasting


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [74]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]  # Swap rows 0 and 1
print(A)


[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [73]:
faces = np.random.randint(0, 100, (10, 3))
F = np.sort(faces, axis=1)
E = np.vstack([F[:, :2], F[:, 1:], F[:, ::2]])
E = np.sort(E, axis=1)
print(np.unique(E, axis=0))


[[ 1 46]
 [ 1 89]
 [ 2 61]
 [ 2 83]
 [ 2 85]
 [ 2 88]
 [ 4 48]
 [ 4 72]
 [10 16]
 [10 19]
 [16 19]
 [18 36]
 [18 55]
 [27 67]
 [27 90]
 [32 86]
 [32 98]
 [36 55]
 [42 70]
 [42 98]
 [46 89]
 [48 72]
 [61 85]
 [65 70]
 [65 91]
 [67 90]
 [70 91]
 [70 98]
 [83 88]
 [86 98]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [72]:
C = np.array([4, 3, 0, 1])
A = np.repeat(np.arange(len(C)), C)
print(A)


[0 0 0 0 1 1 1 3]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [71]:
def moving_average(arr, window):
    return np.convolve(arr, np.ones(window)/window, mode='valid')

Z = np.arange(20)
print(moving_average(Z, 3))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [70]:
Z = np.arange(14)
R = np.lib.stride_tricks.sliding_window_view(Z, window_shape=4)
print(R)


[[ 0  1  2  3]
 [ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [69]:
Z = np.random.randint(0, 2, 10, dtype=bool)
Z = ~Z
print(Z)

F = np.random.uniform(-1, 1, 10)
F *= -1
print(F)


[ True False  True False  True False  True False False False]
[-0.40999874  0.6054287  -0.56640049 -0.4112693  -0.60979946 -0.20529772
 -0.74755535 -0.63410152  0.89334483 -0.61821325]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [68]:
P0 = np.random.rand(10, 2)
P1 = np.random.rand(10, 2)
p = np.random.rand(1, 2)
d = np.abs(np.cross(P1-P0, P0-p))/np.linalg.norm(P1-P0, axis=1)
print(d)


[0.82486458 0.10673278 0.40601312 0.49067494 0.4927712  0.06610638
 0.57410253 0.4937299  0.31214377 0.70460858]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [67]:
P0 = np.random.rand(10, 2)
P1 = np.random.rand(10, 2)
P = np.random.rand(10, 2)
d = np.array([np.abs(np.cross(P1[i] - P0[i], P0[i] - P[j])) / 
              np.linalg.norm(P1[i] - P0[i]) for i in range(len(P0)) for j in range(len(P))])
print(d)


[0.19374254 0.08184744 0.30952448 0.404851   0.47614399 0.08415888
 0.18974432 0.09869279 0.27622942 0.20121268 0.02565386 0.14296133
 0.08913483 0.62017902 0.69468306 0.12209046 0.02715073 0.11850696
 0.49400017 0.01792211 0.04806927 0.04073064 0.08135925 0.68141185
 0.63280185 0.5802928  0.13534444 0.20068352 0.4926757  0.05065046
 0.09494805 0.25338184 0.06776847 0.17275948 0.0352205  0.83826585
 0.24091313 0.19845867 0.06383194 0.11234047 0.03699645 0.37413123
 0.02234004 0.16683511 0.36960555 0.56782695 0.08753652 0.02097882
 0.21843624 0.01954349 0.19691521 0.23496604 0.32701052 0.44826219
 0.4301199  0.2399569  0.1290152  0.05461427 0.26931645 0.19693794
 0.25788359 0.03468816 0.31191701 0.06170439 0.23915977 0.66717127
 0.34907087 0.26562441 0.05219686 0.27365441 0.05856778 0.24374161
 0.02246681 0.41380119 0.23536728 0.86440228 0.20872581 0.20759633
 0.2437797  0.07279355 0.19335707 0.22588424 0.0669535  0.83186007
 0.85592369 0.48469835 0.2324238  0.31655543 0.67259965 0.1897

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [66]:
def extract_subarray(Z, center, shape, fill_value=0):
    pad_width = [(s//2, s//2) for s in shape]
    Z_padded = np.pad(Z, pad_width, constant_values=fill_value)
    center = [c + s//2 for c, s in zip(center, shape)]
    slices = tuple(slice(c-s//2, c+s//2+1) for c, s in zip(center, shape))
    return Z_padded[slices]

Z = np.random.randint(0, 10, (5, 5))
print(extract_subarray(Z, (2, 2), (3, 3), fill_value=-1))


[[0 4 5]
 [9 1 9]
 [1 9 5]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [65]:
Z = np.arange(1, 15, dtype=np.uint32)
R = np.lib.stride_tricks.sliding_window_view(Z, window_shape=4)
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [64]:
Z = np.random.randint(0, 2, (4, 4))
rank = np.linalg.matrix_rank(Z)
print(rank)


3


#### 83. How to find the most frequent value in an array?

In [47]:
Z = np.random.randint(0, 10, 50)
print(np.bincount(Z).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [48]:
Z = np.random.randint(0, 10, (10, 10))
blocks = np.lib.stride_tricks.sliding_window_view(Z, (3, 3))
print(blocks)


[[[[4 7 2]
   [1 8 1]
   [1 5 3]]

  [[7 2 7]
   [8 1 2]
   [5 3 9]]

  [[2 7 2]
   [1 2 4]
   [3 9 4]]

  [[7 2 5]
   [2 4 8]
   [9 4 3]]

  [[2 5 4]
   [4 8 6]
   [4 3 2]]

  [[5 4 9]
   [8 6 2]
   [3 2 4]]

  [[4 9 0]
   [6 2 0]
   [2 4 5]]

  [[9 0 1]
   [2 0 5]
   [4 5 6]]]


 [[[1 8 1]
   [1 5 3]
   [4 3 6]]

  [[8 1 2]
   [5 3 9]
   [3 6 9]]

  [[1 2 4]
   [3 9 4]
   [6 9 6]]

  [[2 4 8]
   [9 4 3]
   [9 6 9]]

  [[4 8 6]
   [4 3 2]
   [6 9 6]]

  [[8 6 2]
   [3 2 4]
   [9 6 3]]

  [[6 2 0]
   [2 4 5]
   [6 3 5]]

  [[2 0 5]
   [4 5 6]
   [3 5 1]]]


 [[[1 5 3]
   [4 3 6]
   [1 5 6]]

  [[5 3 9]
   [3 6 9]
   [5 6 7]]

  [[3 9 4]
   [6 9 6]
   [6 7 1]]

  [[9 4 3]
   [9 6 9]
   [7 1 1]]

  [[4 3 2]
   [6 9 6]
   [1 1 4]]

  [[3 2 4]
   [9 6 3]
   [1 4 9]]

  [[2 4 5]
   [6 3 5]
   [4 9 1]]

  [[4 5 6]
   [3 5 1]
   [9 1 1]]]


 [[[4 3 6]
   [1 5 6]
   [3 6 1]]

  [[3 6 9]
   [5 6 7]
   [6 1 7]]

  [[6 9 6]
   [6 7 1]
   [1 7 6]]

  [[9 6 9]
   [7 1 1]
   [7 6 9]]

  [[6 9 6]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [51]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4 11  8  4 15]
 [11  8  8  7  9]
 [ 8  8  2 42 10]
 [ 4  7 42  1 12]
 [15  9 10 12  8]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [52]:
M = np.random.rand(3, 4, 4)
V = np.random.rand(3, 4, 1)
result = np.einsum('ijk,ikl->jl', M, V)
print(result)

[[2.66747571]
 [3.07118728]
 [3.07063615]
 [2.53692559]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [53]:
Z = np.ones((16, 16))
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], 4), axis=0),
                    np.arange(0, Z.shape[1], 4), axis=1)
print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [54]:
def iterate(Z):
    N = (np.roll(Z, 1, axis=0) + np.roll(Z, -1, axis=0) +
         np.roll(Z, 1, axis=1) + np.roll(Z, -1, axis=1) +
         np.roll(Z, (1, 1), axis=(0, 1)) + np.roll(Z, (1, -1), axis=(0, 1)) +
         np.roll(Z, (-1, 1), axis=(0, 1)) + np.roll(Z, (-1, -1), axis=(0, 1)))
    return (N == 3) | ((Z == 1) & (N == 2))

Z = np.random.randint(0, 2, (10, 10))
for i in range(5):
    Z = iterate(Z)
    print(Z)


[[ True False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False  True False  True]
 [False False False  True False False False False False  True]
 [False  True  True False False False False  True False False]
 [False  True False False False False False False False  True]
 [False False  True False  True False False False False False]
 [False False  True False False False False False False False]
 [ True False False  True False False False False False  True]
 [False False False False False False False False False False]]
[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False Fals

#### 89. How to get the n largest values of an array (★★★)

In [55]:
Z = np.random.randint(0, 100, 10)
n = 3
print(np.sort(Z)[-n:])

[86 97 99]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [56]:
import itertools
A = [1, 2, 3]
B = [4, 5]
C = [6, 7]
print(np.array(list(itertools.product(A, B, C))))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [57]:
Z = np.array([(1, 2.0, 3), (4, 5.0, 6)], dtype='i8,f8,f8')
R = np.core.records.fromarrays(Z.T)
print(R)

((1, 2., 3.), (4, 5., 6.))


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [58]:
Z = np.arange(5)
print(Z**3)  # Method 1
print(np.power(Z, 3))  # Method 2
print(np.einsum('i,i,i->i', Z, Z, Z))  # Method 3

[ 0  1  8 27 64]
[ 0  1  8 27 64]
[ 0  1  8 27 64]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [59]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))
print([row for row in A if all(elem in row for elem in B.flatten())])

[]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [60]:
Z = np.random.randint(0, 5, (10, 3))
print(Z[Z.max(axis=1) != Z.min(axis=1)])


[[1 2 3]
 [3 4 1]
 [3 3 1]
 [4 0 1]
 [2 1 4]
 [0 1 1]
 [0 2 0]
 [2 3 2]
 [3 1 0]
 [0 2 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [61]:
Z = np.array([0, 1, 2, 3, 4, 5])
print(((Z[:, None] & (1 << np.arange(8))) > 0).astype(int))

[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [62]:
Z = np.random.randint(0, 2, (6, 3))
print(np.unique(Z, axis=0))

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [63]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(np.einsum('i,i->', A, B))  # Inner
print(np.einsum('i,j->ij', A, B))  # Outer
print(np.einsum('i->', A))  # Sum
print(np.einsum('i,i->i', A, B))  # Element-wise

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
6
[ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [46]:
A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3))
print(np.maximum(A, B))

[[7 7 8]
 [9 9 8]
 [7 3 7]]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [44]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [45]:
Z = np.random.randint(0, 10, 50)
print(np.unique(Z, return_counts=True))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([4, 5, 5, 8, 5, 5, 6, 1, 4, 7], dtype=int64))
